exclude: 'node_modules'
default_stages: [pre-commit]
default_install_hook_types: [pre-commit, commit-msg]
fail_fast: false

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
        exclude: ".*json$|.*txt$|.*csv|.*md|.*svg"
      - id: end-of-file-fixer
        exclude: ".*json$|.*csv"
      - id: check-merge-conflict
      - id: check-ast
      - id: check-json
      - id: check-toml
      - id: check-yaml
      - id: debug-statements

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.8.1
    hooks:
      - id: ruff
        name: "ruff lint"
        args: ["--fix"]
      - id: ruff-format
        name: "ruff format"

  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v4.0.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]

  - repo: local
    hooks:
      - id: frappe-semgrep
        name: semgrep (frappe rules)
        entry: semgrep --config /home/dev/frappe-semgrep-rules/rules --error --skip-unknown-extensions
        language: system
        types_or: [python, javascript]
        pass_filenames: true
        require_serial: true

      - id: commit-msg-length
        name: check commit message length
        entry: python3
        args:
          - -c
          - |
            import sys
            lines = open(sys.argv[1]).read().splitlines()
            if not lines: sys.exit(0)
            if len(lines[0].strip()) > 72:
                print("Error: Commit subject line too long (> 72 chars).")
                sys.exit(1)
            if len(lines) > 1 and lines[1].strip() != "":
                print("Error: Second line of commit message must be empty.")
                sys.exit(1)
        language: system
        stages: [commit-msg]
